//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management_Football_Pitch
{
    using System;
    using System.Collections.Generic;
    
    public partial class Football_Pitch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Football_Pitch()
        {
            this.Deposit_Invoice = new HashSet<Deposit_Invoice>();
            this.Pitch_Booked = new HashSet<Pitch_Booked>();
        }
    
        public string id_f_pitch { get; set; }
        public string name_pitch { get; set; }
        public string image { get; set; }
        public string type_pitch { get; set; }
        public string address { get; set; }
        public Nullable<decimal> price_1 { get; set; }
        public Nullable<decimal> price_2 { get; set; }
        public Nullable<decimal> price_3 { get; set; }
        public string praren_pitch { get; set; }
        public string state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deposit_Invoice> Deposit_Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pitch_Booked> Pitch_Booked { get; set; }
    }
}
