//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management_Football_Pitch
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pitch_Booked
    {
        public string id_p_book { get; set; }
        public Nullable<System.DateTime> date_book { get; set; }
        public Nullable<System.DateTime> date_use { get; set; }
        public Nullable<System.TimeSpan> time_start { get; set; }
        public Nullable<System.TimeSpan> time_end { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> id_time_slot { get; set; }
        public string id_f_pitch { get; set; }
        public string orderer { get; set; }
        public string phone_orderer { get; set; }
        public string state { get; set; }
    
        public virtual Football_Pitch Football_Pitch { get; set; }
        public virtual Type_Time_Slot Type_Time_Slot { get; set; }
    }
}
