//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management_Football_Pitch
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type_Time_Slot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Type_Time_Slot()
        {
            this.Deposit_Invoice = new HashSet<Deposit_Invoice>();
            this.Pitch_Booked = new HashSet<Pitch_Booked>();
        }
    
        public int id_time_slot { get; set; }
        public string name_time_slot { get; set; }
        public Nullable<System.TimeSpan> time_from { get; set; }
        public Nullable<System.TimeSpan> time_to { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deposit_Invoice> Deposit_Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pitch_Booked> Pitch_Booked { get; set; }
    }
}
